export const dummyData = [
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 100,
    category: "internet bill",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 40,
    category: "water bill",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 250,
    category: "electricity bill",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 30,
    category: "streaming",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 100,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 500,
    category: "grocery",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
  {
    amount: 1200,
    category: "transportation",
    wallet: "Etem Senel",
    date: new Date(),
    note: "",
  },
];
